# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true

# Mod properties
mod_version = 1.4.0
maven_group = dev.sillyangel.nuggetmod
archives_name = nuggetmod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1

# Dependencies
architectury_api_version = 20.0.4
fabric_loader_version = 0.19.3
fabric_api_version = 0.145.1+26.1
neoforge_version = 26.1.0.19-beta
