modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://git.sillyangel.dev/angel/nugget/issues"
license = "MIT"

[[mods]]
modId = "nuggetmod"
version = "${version}"
displayName = "Nugget Mod"
authors = "sillyangel"
description = '''
A Minecraft mod that brings the meme of Gegagedigedagedago Nugget into the Minecraft.
'''
logoFile = "icon.png"
modUrl="https://modrinth.com/mod/nuggetmod"
displayURL="https://modrinth.com/mod/nuggetmod"

[[dependencies.nuggetmod]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.49-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuggetmod]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuggetmod]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "nuggetmod.mixins.json"
